version: '3'
services:
  database:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - ./data/postgres:/data/postgres
    ports:
      - "5432:5432"